---
title: Exceptions and Errors
date: 2018-04-23
description:
  Discussion of Java errors and error handling.
spelling_exceptions:
  - dereferenced
  - incentivize
  - recursed
  - rethrow
  - Rethrowing
echo: https://goo.gl/ymkehW
---
:imagesdir: /learn/images

[[TtJisSLNUcaxKLyWZHfTUBNaEvfKPpGU]]
== !

[.janini.smaller]
--
++++
<div class="message">Exceptions and Errors</div>
++++
....
static void throwError() throws Exception {
  throw new Exception("Exceptions and Errors");
}

try {
  throwError();
} catch (Exception e) {
  System.out.println(e);
}
....
--

[[PuyiTWBrGWwPIAOMQXiVMNbgGWAukMvW]]
== !Warmup Problem

[.janini.compiler.smallest]
....
public class Item {
  public Object key;
  public Object value;
  public Item next;
  Item(Object setKey, Object setValue, Item setNext) {
    this.key = setKey;
    this.value = setValue;
    this.next = setNext;
  }
}
public class HashMap {
  private Item[] items = new Item[16];
  public int keyCount = 0;
  private int hash(Object key) {
    int hashValue = key.hashCode() % 16;
    if (hashValue < 0) {
      hashValue += 16;
    }
    return hashValue;
  }
  public void put(Object key, Object value) {
    int bucket = hash(key);
    Item current = items[bucket];
    for (; current != null; current = current.next) {
      if (current.key.equals(key)) {
        current.value = value;
        return;
      }
    }
    Item newItem = new Item(key, value, items[bucket]);
    items[bucket] = newItem;
    keyCount++;
    return;
  }
  public Object get(Object key) {
    int bucket = hash(key);
    Item current = items[bucket];
    for (; current != null; current = current.next) {
      if (current.key.equals(key)) {
        return current.value;
      }
    }
    return null;
  }
  // Complete the allKeys function below
  public Object[] allKeys() {
    return null;
  }
}
public class Example {
  public static void main(String[] unused) {
    HashMap ourHashMap = new HashMap();
    ourHashMap.put("test", "me");
    ourHashMap.put("test", "another");
    System.out.println(ourHashMap.allKeys());
  }
}
....

[[cfNxpyuNplVjZOGkrvUuWTtPHBfHbdhI]]
[.oneword]
//
== Exceptions
//
Because things go wrong...

[[OzQfgiJWbHOderTtUClGAngECYmlpaNU]]
== Why Exceptions?

[.lead]
//
What do you do when you can't go on?

[source,java]
----
class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
----

[[wkaxBLzVUsfkoRJnKKGGsmhKRjfPqcfS]]
== Why Exceptions?

[.lead]
//
What do you do when you can't go on?

[source,java]
----
/**
 * Read an integer from a passed string
 * and then do something with it.
 */
static int readInteger(final String intAsString) {
  int value = Integer.parseInt(intAsString);
  // But what if intAsString was "foo"?
}
----

[[GnIneJYyrmknSwxawxFLrkfgLTkrkCvS]]
== `try-catch`

[.lead]
//
Java's exception handling control structure is called a `try-catch` block:

[source,java]
----
try {
  // Do something that could cause an exception
} catch (Exception e) {
  // Handle all exceptions that inherit from Exception
}
// Go on if things proceeded normally
----

[[qvlOjZWdEtCQbonLgPsQfGssTFvZwvne]]
== `catch` Matching

[.lead]
//
A `catch` block will match any exceptions that inherit from the one provided.
And they are tried in order.

[[FCwSppBUbsdntJPLYVWUmKhTjmwczUgt]]
== `try-catch` with Multiple `catch`

[.lead]
//
Sometimes you want to handle errors differently depending on what caused them:

[source,java]
----
try {
  // Do something that could cause an exception
} catch (NullPointerException e) {
  // Handle null pointer exceptions
} catch (ArrayIndexOutOfBoundsException e) {
  // Handle array out of bounds exceptions
}
// Go on if things proceeded normally
----

[[qBUvchHqwhTYgXirWtbHjrdzfSozLyed]]
== `try-catch` with Multiple `catch`

[.lead]
//
You can also merge multiple exception types together like this:

[source,java,role='smaller']
----
try {
  // Do something that could cause an exception
} catch (NullPointerException|IllegalArgumentException e) {
  // Handle null pointer and illegal argument exceptions
}
// Go on if things proceeded normally
----

[[chdyOkkmYaXUaZhNnJDZSFXtlEZeXIKv]]
== `try-catch` in Python

[.lead]
//
Many other languages have similar error handling constructs. In Python:

[source,python]
----
try:
  // do something
except ValueError:
  // handle
except Another Error:
  // handle
else:
  // Run if no error is thrown. No analog in Java
finally:
  // Always run
----

[[pLfyzBdmMcJIAnddNqNwBBxPFISVkkIz]]
== `try-catch` in JavaScript

[.lead]
//
Many other languages have similar error handling constructs. In JavaScript:

[source,javascript]
----
try {
  // do something
} catch (err) {
  // handle the err
} finally {
  // Always run
}
----

[[kwZARxJnTlrBuFmKcUMufYbTUVEQzwNm]]
== ! `try-catch` Example

[.janini.smaller]
....
import java.util.Random;

static int throwRandomError() throws Exception {
  Random random = new Random();
  if (random.nextBoolean()) {
    Object it = null;
    return it.hashCode();
  } else {
    int[] array = new int[] {};
    return array[4];
  }
}

// Handle both errors thrown by the function above
throwRandomError();
....

[[jxVCByewgzqbjYjfWzfiuRCWBfuPrfYs]]
== Exceptional Control Flow

[.lead]
//
When an error is thrown control flow _immediately_ jumps to an
enclosing `catch` statement, if one exists.

The `catch` may be in the caller or multiple levels up.

[source,java,role='smallest']
----
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
----

[[YAUdXnxjOpdzBcNRJLgXVKzarNSWNagr]]
== ! `try-catch` with Functions Example


[.janini.smaller]
....
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
foo4();
....


[[YVOVNHgIXQcGbotRhnTLjlRxlloFSLng]]
== Types of Exceptions

[.lead]
//
Java exceptions are broken into three distinct categories:

[.s]
//
* *Checked exceptions*: these are for places where you _know_ something might go
wrong and it's out of your control
//
* *Unchecked exceptions* (or runtime errors): these are usually caused by
something dumb that you (the programmer) did wrong
//
* *Errors*: these are reserved for serious system problems that are probably not
recoverable

[[AglZaxPbaQdMAUyURkopiDaKCMrueDWb]]
== Checked Exceptions: Examples

[.lead]
//
Checked exceptions are for cases where an failure *external to your program* can
cause an exception to occur

[.s]
//
* https://docs.oracle.com/javase/7/docs/api/java/io/FileNotFoundException.html[`FileNotFoundException`]:
//
your program tried to open a file that you expected to exist but it did not
//
* https://docs.oracle.com/javase/7/docs/api/java/net/URISyntaxException.html[`URISyntaxException`]:
//
your program tried to parse a universal resource identifier (URI) but it was
invalid

[[WCoZXcWMWrPzctmXYbUERwsqWmxbhsGH]]
== ! Example Checked Exception

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/net/URISyntaxException.html"></iframe>
</div>
++++

[[JvELdFMCwSnXRmghdAhhglEfbojSOHJI]]
== Checked Exceptions: Handling

[.lead]
//
If you use a function that may generate a checked exception, you must either
wrap it in a `try-catch` block or declare that you may throw it.

[source,role='s smaller']
----
static URI createURI(final String input) {
  // Example where we handle URISyntaxExceptions
  try {
    return new URI(input);
  } catch (URISyntaxException e) {
    System.out.println(input + " is not a valid URI");
  }
}
----

[source,role='s smaller mt-2']
----
// Example where we throw URISyntaxExceptions
static URI createURI(final String input) throws URISyntaxException {
  return new URI(input);
}
----

[[lTSokCKduCxcHhdvMeDXSCDpGcryAMul]]
== ! Checked Exceptions: Handling Example

[.janini.smaller]
....
import java.net.URI;
static URI createURI(final String input) {
  return new URI(input);
}
System.out.println(createURI("https://cs125.cs.illinois.edu/"));
....

[[OfiMUvDfLqHrmsHHbwRRrxkkLLWCItZx]]
== Unchecked Exceptions: Examples

[.lead]
//
Unchecked examples are usually the result of _programmer error_.

You've probably made many of these mistakes by now...

[.s.small]
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/ArrayIndexOutOfBoundsException.html[`ArrayIndexOutOfBoundsException`]:
//
[.s]#you walked off the end of an array#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/NullPointerException.html[`NullPointerException`]:
//
[.s]#you dereferenced a `null` reference#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/ClassCastException.html[`ClassCastException`]:
//
[.s]#you tried to cast something to a subclass of which it is not an instance#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalArgumentException.html[`IllegalArgumentException`]:
//
[.s]#you passed incorrect arguments to a function or constructor#

[[KXOYoGDTpyttOUMGgFJomhMqvznzGXoE]]
== Unchecked Exceptions: Handling

[.lead]
//
Unlike checked exceptions, you do not need to declare or handle unchecked
exceptions.

However, you _can_ handle them:

[source,java,role='s smaller']
----
try {
  String s = callMyPartnersDodgyCode();
  if (s.length() == 0) {
    return;
  }
} catch (NullPointerException e) {
  return;
}
----

[[cOoeHZUWDypFrxsatLfQZXqrMnvSBIWc]]
== Final Project Reminders

[.lead]
//
You have less than two weeks to complete your final project!

[.s]
//
* *You need a partner.* You're about to lose 20 points if you don't have one.
//
* *You need a UI.* See above.
//
* *Have fun!*
//
* _Questions_?

[[dzObIAUNjSBldZMkzRYoEOfeXeEoLEwG]]
== ICES Plan and Incentives

[.lead]
//
The way that we do ICES is really dumb...

[.s]
//
* We'll be doing our own custom end-of-semester survey, so you'll have a chance
to fill out an evaluation online like a normal human being.
//
* (And we'll get the feedback before the class is offered multiple more times.)
//

[[EnldllNIUKAzxdDshUdAUALUcbqcXeBr]]
== ICES Plan and Incentives

[.lead]
//
...but I still want you to complete the ICES forms.
//
*So to incentivize participation*:

[.s.small]
//
* If you get to 70% I'll release one of the short programming problems from the
exam
//
* If you get to 80% I'll release _another_ programming problem from the
exam
//
* If you get to 90% I'll release *a hard* programming problem from the
exam
//
* Note that the TAs will be supervising the ICES forms so that I can trust the
count. And the 8AM and 10AM classes are in this together.

[[oViMXZJHRuOiNPZSUiHsapzzDrHNNTpN]]
== Announcements

* link:/MP/7/[MP7 (the final project)] is out.
//
Please get started!
//
* The
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
remains available on the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
